#!/usr/bin/env python3
"""Discover what is in a JSON Lines trace. Standard library only.

This is deliberately NOT a parser: it counts records by their `type` field and
prints raw examples verbatim. Nothing here interprets a field's meaning, so it
cannot go stale or encode a guess about the recording format.

    python tools/inspect_trace.py runs/fixture.jsonl
    python tools/inspect_trace.py runs/fixture.jsonl --write

--write dumps the same output to notes/schema.md (overwriting it) so it can be
pasted straight into a chat.
"""

import argparse
import json
import os
import sys


def scan(path, warn):
    """Stream the file once. Returns (order, counts, first, last_type, stats)."""
    counts = {}      # type -> number of records
    first = {}       # type -> first record seen, unmodified
    order = []       # types in order of first appearance
    last_type = None
    lines = parsed = skipped = 0

    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            lines += 1
            stripped = line.strip()
            if not stripped:
                continue          # trailing blank line is normal
            try:
                record = json.loads(stripped)
            except ValueError as exc:
                skipped += 1
                warn("line %d is not valid JSON (%s)" % (lines, exc))
                continue
            parsed += 1
            if isinstance(record, dict):
                kind = str(record.get("type", "<no-type-field>"))
            else:
                kind = "<not-an-object:%s>" % type(record).__name__
            if kind not in counts:
                counts[kind] = 0
                first[kind] = record
                order.append(kind)
            counts[kind] += 1
            last_type = kind

    stats = {"lines": lines, "parsed": parsed, "skipped": skipped}
    return order, counts, first, last_type, stats


def render(path, order, counts, first, last_type, stats):
    """Build the report as markdown: readable in a terminal, pastes cleanly."""
    out = []
    add = out.append

    add("# Trace contents: %s" % os.path.basename(path))
    add("")
    add("Generated by `tools/inspect_trace.py`. Raw records, nothing interpreted.")
    add("")
    add("| | |")
    add("| --- | --- |")
    add("| file | `%s` |" % path)
    add("| size | %d bytes |" % os.path.getsize(path))
    add("| lines | %d |" % stats["lines"])
    add("| parsed | %d |" % stats["parsed"])
    add("| skipped | %d |" % stats["skipped"])
    add("| last record type | `%s` |" % last_type)
    add("")

    add("## Record types")
    add("")
    add("| type | count |")
    add("| --- | --- |")
    for kind in sorted(order, key=lambda k: -counts[k]):
        add("| `%s` | %d |" % (kind, counts[kind]))
    add("")

    def dump(kind, heading):
        add("## %s" % heading)
        add("")
        add("```json")
        add(json.dumps(first[kind], indent=2, sort_keys=False))
        add("```")
        add("")

    # The header record defines the frame column names, so it gets its own
    # section at the top as well as its place in the sequence below.
    if "header" in first:
        dump("header", "`header` record (defines the frame column names)")

    for kind in order:
        dump(kind, "First `%s` record" % kind)

    return "\n".join(out) + "\n"


def main(argv):
    parser = argparse.ArgumentParser(
        description="Count record types in a JSON Lines trace and print raw examples.")
    parser.add_argument("trace", help="path to the .jsonl recording")
    parser.add_argument("--write", nargs="?", const=os.path.join("notes", "schema.md"),
                        default=None, metavar="PATH",
                        help="also write the report to PATH (default: notes/schema.md)")
    args = parser.parse_args(argv[1:])

    if not os.path.isfile(args.trace):
        print("no such file: %s" % args.trace, file=sys.stderr)
        return 1

    warnings = []

    def warn(message):
        warnings.append(message)
        print("warning: %s" % message, file=sys.stderr)

    order, counts, first, last_type, stats = scan(args.trace, warn)
    if stats["parsed"] == 0:
        print("no records parsed -- is %s empty? (the simulator writes the "
              "trace at the end of the run, not during it)" % args.trace,
              file=sys.stderr)
        return 1

    report = render(args.trace, order, counts, first, last_type, stats)
    sys.stdout.write(report)

    if args.write:
        directory = os.path.dirname(args.write)
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(args.write, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(report)
        print("\nwrote %s" % args.write, file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
